export const allServices = [
  { id: 'services', img: '/Images/all services images:icons/ծառայություններ/ծառայություններ.webp', icon: '/Images/all services images:icons/ծառայություններ/beauty.webp', title: 'Ծառայություններ' },
  { id: 'face-cleaning', img: '/Images/all services images:icons/դեմքի մաքրում/դեմքի մաքրում և խնամք.webp', icon: '/Images/all services images:icons/դեմքի մաքրում/դեմքի մաքրում icon.svg', title: 'Դեմքի Մաքրում և Խնամք' },
  { id: 'peelings', img: '/Images/all services images:icons/Pilings/պիլինգներ.webp', icon: '/Images/all services images:icons/Pilings/piling icon.svg', title: 'Պիլինգներ' },
  { id: 'aparatayin', img: '/Images/all services images:icons/ապարատային կոսմ./ապարատային կոսմետոլոգիա.webp', icon: '/Images/all services images:icons/ապարատային կոսմ./ապարատային icon.svg', title: 'Ապարատային կոսմետոլոգիա' },
  { id: 'aparatayin2', img: '/Images/Service/aparatayin2.png', icon: '/Images/all services images:icons/ապարատային կոսմ./ապարատային icon.svg', title: 'Ապարատային կոսմետոլոգիա 2' },
  { id: 'laser', img: '/Images/all services images:icons/մազահեռացում/մազահեռացում.webp', icon: '/Images/all services images:icons/մազահեռացում/մազահեռացում icon.svg', title: 'Լազերային մազահեռացում' },
  { id: 'mazahertatsoom', img: '/Images/Service/mazaheracum2.png', icon: '/Images/all services images:icons/մազահեռացում/մազահեռացում icon.svg', title: 'Մազահեռացում' },
  { id: 'nerarkoumner', img: '/Images/all services images:icons/ներարկումներ/ներարկումներ.webp', icon: '/Images/all services images:icons/ներարկումներ/ներարկումներ icon.svg', title: 'Ներարկումներ' },
  { id: 'dajvadz', img: '/Images/all services images:icons/Tattoo/tattoo.webp', icon: '/Images/all services images:icons/Tattoo/tattoo icon.svg', title: 'Դաջվածք' },
  { id: 'aqua', img: '/Images/all services images:icons/AQUA/AQUA.webp', icon: '/Images/all services images:icons/AQUA/AQUA icon.svg', title: 'AQUA' },
  { id: 'akne', img: '/Images/Service/New procedures/ACNE.webp', icon: '/Images/all services images:icons/acne/acne.svg', title: 'Ակնե' },
  { id: 'antiage', img: '/Images/all services images:icons/Anti Age/ANTI AGE.webp', icon: '/Images/all services images:icons/Anti Age/anti age icon.svg', title: 'ANTI AGE' },
  { id: 'antiageblock', img: '/Images/all services images:icons/anti age block/anti age block.webp', icon: '/Images/all services images:icons/anti age block/anti age block.svg', title: 'ANTI AGE BLOCK' },
  { id: 'blockage', img: '/Images/all services images:icons/Block Age/Block age.webp', icon: '/Images/all services images:icons/Block Age/block age icon.svg', title: 'BLOCK AGE' },
  { id: 'nayvapackage', img: '/Images/all services images:icons/N Ayva Package/N Ayva package.webp', icon: '/Images/all services images:icons/N Ayva Package/n ayva package icon.svg', title: 'N.Ayva Փաթեթ' },
  { id: 'marmnikorekcia', img: '/Images/all services images:icons/մարմնի կորեկցիա/մարմնի կորեկցիա.webp', icon: '/Images/all services images:icons/մարմնի կորեկցիա/մարմնի կորեկցիա.svg', title: 'Մարմնի կորեկցիա' },
  { id: 'marmnialone', img: '/Images/Service/marmni korekcia2.png', icon: '/Images/all services images:icons/մարմնի կորեկցիա/մարմնի կորեկցիա.svg', title: 'Մարմնի կորեկցիա առանձին' },
];
